#+TITLE:       The Manifesto
#+AUTHOR:      James Taylor
#+EMAIL:       james@openmail.cc
#+DATE:        2018-06-18 Mon
#+URI:         /the-manifesto
#+KEYWORDS:    manifesto, principles, ideas
#+TAGS:        philosophy
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: The Manifesto
*Concerning those principles of greatest merit to the modern tinkerer, herein explained...*

* Curiosity

The tinkerer is always "on the prowl" for new ideas and projects, never knowing what might give them inspiration or prove to be exciting. They are curious about the points of view of other people and see opportunities to explore everywhere.


* Adventurousness

The tinkerer does not favor the familiar over the novel. They do not crave novelty, but love a good chance to explore. What a tinkerer finds to be functional, they will keep, but the everlasting question in their mind will be "Is this really the only way?"


* Generosity

The tinkerer knows that knowledge and ideas are not property, but are drops in an ever-growing ocean of human understanding. The tinkerer would no sooner keep their ideas a  secret than deprive a thirsty person of water. We all thirst for something, and the tinkerer is in the unique position to have a little to give to others. Cherish this gift and impart it to others freely.


* Modesty

The tinkerer does not have all the answers, and they know it. They are a perpetual student who does not feign expertise or claim authority. Instead, they listen, question, and learn, no matter how much they already know. A tinkerer must always be ready for criticism and growth.


* Humor

Tinkerers make mistakes, and some of these mistakes may demolish what they are trying to do. The tinkerer knows how to laugh about this and try a different approach.






